/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ComponentsImport } from './routes/components'
import { Route as IndexImport } from './routes/index'
import { Route as DocsIndexImport } from './routes/Docs/index'
import { Route as ComponentsAnimatedButtonImport } from './routes/components/animated-button'
import { Route as DocsDocsIdImport } from './routes/Docs/$docsId'

// Create Virtual Routes

const ComponentsAllComponentsLazyImport = createFileRoute(
  '/components/all-components',
)()

// Create/Update Routes

const ComponentsRoute = ComponentsImport.update({
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DocsIndexRoute = DocsIndexImport.update({
  path: '/Docs/',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsAllComponentsLazyRoute =
  ComponentsAllComponentsLazyImport.update({
    path: '/all-components',
    getParentRoute: () => ComponentsRoute,
  } as any).lazy(() =>
    import('./routes/components/all-components.lazy').then((d) => d.Route),
  )

const ComponentsAnimatedButtonRoute = ComponentsAnimatedButtonImport.update({
  path: '/animated-button',
  getParentRoute: () => ComponentsRoute,
} as any)

const DocsDocsIdRoute = DocsDocsIdImport.update({
  path: '/Docs/$docsId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsImport
      parentRoute: typeof rootRoute
    }
    '/Docs/$docsId': {
      id: '/Docs/$docsId'
      path: '/Docs/$docsId'
      fullPath: '/Docs/$docsId'
      preLoaderRoute: typeof DocsDocsIdImport
      parentRoute: typeof rootRoute
    }
    '/components/animated-button': {
      id: '/components/animated-button'
      path: '/animated-button'
      fullPath: '/components/animated-button'
      preLoaderRoute: typeof ComponentsAnimatedButtonImport
      parentRoute: typeof ComponentsImport
    }
    '/components/all-components': {
      id: '/components/all-components'
      path: '/all-components'
      fullPath: '/components/all-components'
      preLoaderRoute: typeof ComponentsAllComponentsLazyImport
      parentRoute: typeof ComponentsImport
    }
    '/Docs/': {
      id: '/Docs/'
      path: '/Docs'
      fullPath: '/Docs'
      preLoaderRoute: typeof DocsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ComponentsRoute: ComponentsRoute.addChildren({
    ComponentsAnimatedButtonRoute,
    ComponentsAllComponentsLazyRoute,
  }),
  DocsDocsIdRoute,
  DocsIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.ts",
      "children": [
        "/",
        "/components",
        "/Docs/$docsId",
        "/Docs/"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/components": {
      "filePath": "components.ts",
      "children": [
        "/components/animated-button",
        "/components/all-components"
      ]
    },
    "/Docs/$docsId": {
      "filePath": "Docs/$docsId.tsx"
    },
    "/components/animated-button": {
      "filePath": "components/animated-button.tsx",
      "parent": "/components"
    },
    "/components/all-components": {
      "filePath": "components/all-components.lazy.tsx",
      "parent": "/components"
    },
    "/Docs/": {
      "filePath": "Docs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
